apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: msevcik-ambulance-ufe-content
spec:
  microFrontend: msevcik-ambulance-ufe
  element: msevcik-ambulance-wl-app
  attributes:
    - name: base-path
      value: /msevcik-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?msevcik-ambulance-wl(/.*)?$"